server:
  port: 8088
  servlet:
    context-path: /springboot
name: jiang
age: 26

person:
  name: jiangyongkang
  age: 26
  school: hfut

#配置视图解析器
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
